Update python-app.yml (#45)
* Update python-app.yml 

- Replace conda install, see https://github.com/s-weigand/setup-conda/issues/432
- Update https://github.com/actions/checkout

* Use ts-graphviz/setup-graphviz@v2

See https://github.com/marketplace/actions/setup-graphviz
Replaces `conda install -c anaconda graphviz` on MacOS

* Use psycopg2-binary 

Fixes
```
 Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
```

* Update setup.py